"""initial schema

Revision ID: b4d9a8e793cc
Revises: 
Create Date: 2026-04-01 12:21:18.388132
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers
revision: str = 'b4d9a8e793cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_run_org', 'agent_runs', ['org_id'], unique=False)
    op.create_index('idx_agent_run_project', 'agent_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_org_id'), 'agent_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_project_id'), 'agent_runs', ['project_id'], unique=False)
    op.create_table('discrepancy_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('spec_doc_ids', sa.JSON(), nullable=True),
    sa.Column('submittal_doc_ids', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('discrepancy_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disc_report_org', 'discrepancy_reports', ['org_id'], unique=False)
    op.create_index('idx_disc_report_project', 'discrepancy_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_discrepancy_reports_org_id'), 'discrepancy_reports', ['org_id'], unique=False)
    op.create_index(op.f('ix_discrepancy_reports_project_id'), 'discrepancy_reports', ['project_id'], unique=False)
    op.create_table('discrepancy_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spec_reference', sa.String(length=255), nullable=True),
    sa.Column('spec_doc_id', sa.Integer(), nullable=True),
    sa.Column('spec_page', sa.Integer(), nullable=True),
    sa.Column('spec_excerpt', sa.Text(), nullable=True),
    sa.Column('submittal_reference', sa.String(length=255), nullable=True),
    sa.Column('submittal_doc_id', sa.Integer(), nullable=True),
    sa.Column('submittal_page', sa.Integer(), nullable=True),
    sa.Column('submittal_excerpt', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['discrepancy_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disc_item_report', 'discrepancy_items', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_disc_item_report', table_name='discrepancy_items')
    op.drop_table('discrepancy_items')
    op.drop_index(op.f('ix_discrepancy_reports_project_id'), table_name='discrepancy_reports')
    op.drop_index(op.f('ix_discrepancy_reports_org_id'), table_name='discrepancy_reports')
    op.drop_index('idx_disc_report_project', table_name='discrepancy_reports')
    op.drop_index('idx_disc_report_org', table_name='discrepancy_reports')
    op.drop_table('discrepancy_reports')
    op.drop_index(op.f('ix_agent_runs_project_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_org_id'), table_name='agent_runs')
    op.drop_index('idx_agent_run_project', table_name='agent_runs')
    op.drop_index('idx_agent_run_org', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
